title:              Johnny Terraform
#email:              your-email@example.com
description:        A Blog about things I do with Terraform and maybe some other stuff.
author:             John Stephen
baseurl:            "/page-things"
url:                "https://jsol3jx.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    jsol3jx
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username: johnstephen

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
